import 'package:flutter/material.dart';
import 'package:mina_s_application5/core/utils/pref_utils.dart';
import 'package:mina_s_application5/core/utils/size_utils.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generatorif (!_supportedCustomColor.containsKey(_appTheme)){  throw Exception(               "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");      } //return theme from map
    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator if (!_supportedColorScheme.containsKey(_appTheme)){   throw Exception(                "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");       }  //return theme from map
    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.gray100,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.amber700,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: appTheme.amber700,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyMedium: TextStyle(
          color: appTheme.blueGray900,
          fontSize: 14.fSize,
          fontFamily: 'SF Pro Text',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.gray700,
          fontSize: 10.fSize,
          fontFamily: 'SF Pro Text',
          fontWeight: FontWeight.w400,
        ),
        labelLarge: TextStyle(
          color: appTheme.gray800,
          fontSize: 13.fSize,
          fontFamily: 'Sulphur Point',
          fontWeight: FontWeight.w700,
        ),
        labelMedium: TextStyle(
          color: colorScheme.secondaryContainer,
          fontSize: 11.fSize,
          fontFamily: 'Sulphur Point',
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: appTheme.gray70001,
          fontSize: 20.fSize,
          fontFamily: 'SF Pro Text',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: appTheme.gray900,
          fontSize: 16.fSize,
          fontFamily: 'SF Pro Text',
          fontWeight: FontWeight.w600,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 15.fSize,
          fontFamily: 'SF Pro Text',
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF017CBA),
    secondaryContainer: Color(0XFF4C4C4C),

    // On colors(text colors)
    onPrimary: Color(0XFFFFFFFF),
    onPrimaryContainer: Color(0XFFC40A0A),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber (now primary green – kept name for compatibility)
  Color get amber700 => const Color(0xFF1F9B3F);

  // Black
  Color get black900 => const Color(0xFF000000);

  // Blue (kept as-is for structure / contrast)
  Color get blue100 => const Color(0xFFBFDEEE);
  Color get blue50 => const Color(0xFFE3F2F9);
  Color get blue5001 => const Color(0xFFE4F3F9);

  // BlueGray
  Color get blueGray100 => const Color(0xFFD9D9D9);
  Color get blueGray10023 => const Color(0x23D4D4D4);
  Color get blueGray900 => const Color(0xFF2B2B2B);

  // DeepOrange (now very light green tint)
  Color get deepOrange50 => const Color(0xFFEAF6EF);

  // Gray (kept – good neutral system)
  Color get gray100 => const Color(0xFFF7F7F7);
  Color get gray300 => const Color(0xFFDCD9D9);
  Color get gray30001 => const Color(0xFFDDDADA);
  Color get gray400 => const Color(0xFFBABABA);
  Color get gray500 => const Color(0xFFB0ABAB);
  Color get gray50021 => const Color(0x21AAAAAA);
  Color get gray700 => const Color(0xFF63656A);
  Color get gray70001 => const Color(0xFF55565B);
  Color get gray70060 => const Color(0x60565656);
  Color get gray800 => const Color(0xFF4A4A4A);
  Color get gray900 => const Color(0xFF2A2A2A);

  // LightGreen (aligned with new logo greens)
  Color get lightGreenA700 => const Color(0xFF0B852A);
  Color get lightGreenA70001 => const Color(0xFF137D2E);
  Color get lightGreenA70002 => const Color(0xFF1D8F35);

  // Orange (now green accent – name kept)
  Color get orange300 => const Color(0xFF1F9B3F);
  Color get orange50 => const Color(0xFFEAF6EF);

  // Purple (kept – optional accent)
  Color get purple100 => const Color(0xFFECCCF2);
  Color get purple300 => const Color(0xFFCA6DD9);

  // Teal (kept as soft background)
  Color get teal50 => const Color(0xFFDEEBF2);

  // Derived
  Color get totalRowColor => orange300.withOpacity(0.50);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
